name: "generate-version-and-release-notes"
description: "generates semver and changelog.md after a pull request has been merge"
inputs:
  user-email:
    description: "email to sign the commit that will be pushed to main branch"
    required: true
  user-name:
    description: "name to sign the commit that will be pushed to main branch"
    required: true
    default: "GitHub Actions"
  skip-git-commit:
    description: "Specify if git commit should be skipped for changed files. Default is false - meaning, files are committed and commit is tagged and pushed"
    required: false
    default: "false"
  version-prefix:
    description: "Prefix to put immediately before the version number when tagging. Example: v0.1.4, beta-1.4.2"
    required: false
    default: ""
outputs:
  service-version:
    description: 'Service version'
    value: ${{ steps.service-version.outputs.service-version }}
runs:
  using: "composite"
  steps:
    - run: |
        git config user.email ${{ inputs.user-email }}
        git config user.name ${{ inputs.user-name }}
        node ${{ github.action_path }}/../generate-version-and-release-notes.js ${{ inputs.skip-git-commit }} ${{ inputs.version-prefix }}
      shell: bash
    - id: service-version
      run: echo "::set-output name=service-version::$(cat ./version.json | jq -r '.version')"
      shell: bash
