name: "generate-version-and-release-notes"
description: "generates semver and changelog.md after a pull request has been merge"
inputs:
  user-email:
    description: "email to sign the commit that will be pushed to main branch"
    required: true
  user-name:
    description: "name to sign the commit that will be pushed to main branch"
    required: true
    default: "GitHub Actions"
outputs:
  service-version:
    description: 'Service version'
    value: ${{ steps.service-version.outputs.service-version }}
runs:
  using: "composite"
  steps:
    - run: |
        git config user.email ${{ inputs.user-email }}
        git config user.name ${{ inputs.user-name }}
        node ${{ github.action_path }}/../generate-version-and-release-notes.js
      shell: bash
    - id: service-version
      run: echo "::set-output name=service-version::$(cat ./version.json | jq -r '.version')"
      shell: bash
