name: "terraform-plan"
description: "plans a terraform configuration"
inputs:
  region:
    description: "aws region name"
    required: true
  access-key:
    description: "access key"
    required: true
  secret-key:
    description: "secret key"
    required: true
  account: #FIXME we can remove it because there is wrong order in script
    description: "aws account id"
    required: true
  terraform-folder:
    description: "folder where your terraform configuration is"
    required: true
  backend-configuration:
    description: "file with additional backend configuration"
    required: true
  terraform-var-file:
    description: "file with the terraform variables (.tfvars or .tfvars.json)"
    required: true
  terraform-plan-file:
    description: "file where terraform will put the proposed plan"
    required: true
  destroy-mode:
    description: "Plans a destroy action. false(default value)=>normal flow, true=>destroy mode."
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/../tfm-plan.sh ${{ inputs.region }} ${{ inputs.access-key }} ${{ inputs.secret-key }} ${{ inputs.account }} ${{ inputs.terraform-folder }} ${{ inputs.backend-configuration }} ${{ inputs.terraform-var-file }} ${{ inputs.terraform-plan-file }} ${{ inputs.destroy-mode }}
      shell: bash
