name: "ensure-conventional-commits"
description: "checks that the commits in a pull request follow conventional commits"
inputs:
  base-branch:
    description: "name of the branch where the pull request goes to"
    required: true
  pr-branch:
    description: "name of the branch where the pull request comes from"
    required: true
runs:
  using: "composite"
  steps:
    - run: node ${{ github.action_path }}/../ensure-conventional-commits.sh ${{ inputs.base-branch }} ${{ inputs.pr-branch }}
      shell: bash
