name: "create-or-update-stack"
description: "creates (or updates) an stack based on cfn inputs"
inputs:
  region:
    description: "aws region name"
    required: true
  access-key:
    description: "access key"
    required: true
  secret-key:
    description: "secret key"
    required: true
  account:
    description: "aws account id"
    required: true
  role-name:
    description: "role to assume"
    required: true
  stack-name:
    description: "name of the stack to update"
    required: true
  template-body-path:
    description: "path where the cloudformation template file is located"
    required: true
  cfn-parameters-path:
    description: "path where the cloudformation inputs are located"
    required: true
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/../create-or-update-stack.sh ${{ inputs.region }} ${{ inputs.access-key }} ${{ inputs.secret-key }} ${{ inputs.account }} ${{ inputs.role-name }} ${{ inputs.stack-name }} ${{ inputs.template-body-path }} ${{ inputs.cfn-parameters-path }}
      shell: bash
